
services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    volumes:
      - ./assets/:/www/assets
    ports:
      - 8080:8080  
    user: 1000:1000 
    env_file:
      - .env
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: unless-stopped      
